import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { AppSidebar } from "@/components/blocks/app-sidebar";
import { AppTaskbar } from "@/components/blocks/app-taskbar";
import { SearchCommand } from "@/components/blocks/search-command";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex h-screen w-full">
            <AppSidebar />
            <main className="flex-1 flex flex-col bg-foreground overflow-hidden">
              <AppTaskbar />
              <div className="flex-1 mr-2 mb-3 rounded-2xl bg-white overflow-hidden">
                <ScrollArea className="h-full">
                  {children}
                </ScrollArea>
              </div>
            </main>
          </div>
          <SearchCommand />
        </SidebarProvider>
      </body>
    </html>
  );
}
